name: Sync Fork

on:
  schedule:
    - cron: '* 12 * * *' # 12:00 everyday
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: NimaQu/fork-sync@v1.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: happy888888
          base: master
          head: master
          token_merge: true
          personal_token: ${{ secrets.PERSONAL_TOKEN }}